actions:
  pre:
    bash_it_submodules: git submodule update --init --recursive dotfiles/config/bash_it
    tmux_submodules: git submodule update --init --recursive dotfiles/tmux/plugins/tpm
  post:
    asdf_install: cd "$HOME" && [ -d .asdf ] && asdf install
    bash_it: '"$HOME/.bash_it/install.sh" --silent --no-modify-config'
    direnv_allow: direnv allow "{0}"
    gpg_agent_reload: gpgconf --kill gpg-agent
    my_eyes_only_dir: chmod 700 "{{@@ dirname(_dotfile_abs_dst) @@}}"
    tmux_plugins:
      cd "$HOME/.tmux/plugins/tpm/bin" && ./clean_plugins && ./install_plugins
      && ./update_plugins all
    vim_plugins: nvim +PlugClean! +PlugInstall +PlugUpdate +qall
config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
dotfiles:
  d_bash_it:
    actions:
      - bash_it_submodules
      - bash_it
    dst: ~/.bash_it
    src: config/bash_it
  d_ctags.d:
    dst: ~/.ctags.d
    src: ctags.d
  d_fontconfig:
    dst: ~/.config/fontconfig
    src: config/fontconfig
  d_git:
    dst: ~/.config/git
    src: config/git
  d_github:
    dst: ~/.config/.github
    src: config/.github
  d_openbox:
    dst: ~/.config/openbox
    src: config/openbox
  d_tmux:
    actions:
      - tmux_submodules
      - tmux_plugins
    dst: ~/.tmux/plugins/tpm
    src: tmux/plugins/tpm
  d_xmonad:
    dst: ~/.xmonad
    src: xmonad
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_emacs:
    dst: ~/.emacs
    src: emacs
  f_gemrc:
    dst: ~/.gemrc
    src: gemrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore_global:
    dst: ~/.config/gitignore_global
    src: config/gitignore_global
  f_hgrc:
    dst: ~/.hgrc
    src: hgrc
  f_lightson+:
    dst: ~/.local/bin/lightson+
    src: local/bin/lightson+
  f_plug.vim:
    dst: ~/.local/share/nvim/site/autoload/plug.vim
    src: local/share/nvim/site/autoload/plug.vim
  f_profile:
    dst: ~/.profile
    src: profile
  f_pylintrc:
    dst: ~/.pylintrc
    src: pylintrc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    actions:
      - vim_plugins
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_vscode_settings:
    dst: ~/.config/Code - OSS/User/settings.json
    src: config/Code - OSS/User/settings.json
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xorg.conf:
    dst: ~/xorg.conf
    src: xorg.conf
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_xscreensaver:
    dst: ~/.xscreensaver
    src: xscreensaver
  f_tool-versions:
    actions:
      - asdf_install
    src: tool-versions
    dst: ~/.tool-versions
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  f_envrc:
    actions:
      - direnv_allow "{@@ dst @@}"
    src: envrc
    dst: ~/.envrc
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_gpg.conf:
    actions:
      - my_eyes_only_dir
    src: gnupg/gpg.conf
    dst: ~/.gnupg/gpg.conf
  f_gpg-agent.conf:
    actions:
      - my_eyes_only_dir
      - gpg_agent_reload
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_default-python-packages:
    src: default-python-packages
    dst: ~/.default-python-packages
  f_autostart:
    src: config/lxsession/LXDE/autostart
    dst: ~/.config/lxsession/LXDE/autostart
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_wakatime.cfg:
    src: wakatime.cfg
    dst: ~/.wakatime.cfg
    trans_read: _gpg
variables:
  gpg_password: "lpass show --password 'gpg proton'"
trans_read:
  _gpg: "echo {{@@ gpg_password @@}} | gpg2 --batch --yes --passphrase-file /dev/stdin -q --for-your-eyes-only --no-tty -d {0} > {1}"
profiles:
  base_profile:
    dotfiles:
      - d_bash_it
      - d_ctags.d
      - d_fontconfig
      - d_git
      - d_github
      - d_tmux
      - f_bashrc
      - f_default-python-packages
      - f_editorconfig
      - f_emacs
      - f_envrc
      - f_gemrc
      - f_gitconfig
      - f_gitignore_global
      - f_gpg-agent.conf
      - f_gpg.conf
      - f_hgrc
      - f_inputrc
      - f_plug.vim
      - f_profile
      - f_pylintrc
      - f_tmux.conf
      - f_tool-versions
      - f_vimrc
      - f_vscode_settings
      - f_bash_profile
      - f_wakatime.cfg
  lxde_profile:
    dotfiles:
      - d_openbox
      - f_autostart
      - f_lightson+
      - f_xorg.conf
      - f_xprofile
      - f_xresources
      - f_xscreensaver
  reds-machine:
    include:
      - base_profile
      - lxde_profile
  xmonad_profile:
    dotfiles:
      - d_xmonad
  zeta:
    include:
      - base_profile
