actions:
  bash_it: $HOME/.bash_it/install.sh --silent --no-modify-config
  pre:
    bash_it_submodules: git submodule update --init --recursive dotfiles/config/bash_it
    vim_plugins_submodules: git submodule update --init --recursive dotfiles/config/nvim/bundle
  vim_plugins: nvim +PluginClean! +PluginInstall +PluginUpdate +qall && "$HOME/.config/nvim/bundle/YouCompleteMe/install.py"
    --clang-completer --racer-completer --system-libclang --system-boost
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_bash_it:
    actions:
    - bash_it_submodules
    - bash_it
    dst: ~/.bash_it
    link: true
    src: config/bash_it
  d_ctags.d:
    dst: ~/.ctags.d
    src: ctags.d
  d_fontconfig:
    dst: ~/.config/fontconfig
    src: config/fontconfig
  d_git:
    dst: ~/.config/git
    src: config/git
  d_github:
    dst: ~/.config/.github
    src: config/.github
  d_openbox:
    dst: ~/.config/openbox
    src: config/openbox
  d_vundle.vim:
    dst: ~/.config/nvim/bundle/Vundle.vim
    src: config/nvim/bundle/Vundle.vim
    actions:
      - vim_plugins_submodules
    link: true
  d_xmonad:
    dst: ~/.xmonad
    src: xmonad
  f_asoundrc:
    dst: ~/.asoundrc
    src: asoundrc
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_emacs:
    dst: ~/.emacs
    src: emacs
  f_gemrc:
    dst: ~/.gemrc
    src: gemrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore_global:
    dst: ~/.config/gitignore_global
    src: config/gitignore_global
  f_hgrc:
    dst: ~/.hgrc
    src: hgrc
  f_nvidia-settings-rc:
    dst: ~/.nvidia-settings-rc
    src: nvidia-settings-rc
  f_profile:
    dst: ~/.profile
    src: profile
  f_pylintrc:
    dst: ~/.pylintrc
    src: pylintrc
  f_rvmrc:
    dst: ~/.rvmrc
    src: rvmrc
  f_vimrc:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
    actions:
      - vim_plugins
  f_vscode_settings:
    dst: ~/.config/Code - OSS/User/settings.json
    src: config/Code - OSS/User/settings.json
    link: true
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
profiles:
  Toxicity:
    dotfiles:
    - f_asoundrc
    - f_xinitrc
    - f_nvidia-settings-rc
    include:
    - base_profile
  base_profile:
    dotfiles:
    - d_ctags.d
    - d_bash_it
    - d_fontconfig
    - d_git
    - d_github
    - d_openbox
    - d_vundle.vim
    - d_xmonad
    - f_emacs
    - f_gemrc
    - f_gitconfig
    - f_gitignore_global
    - f_hgrc
    - f_pylintrc
    - f_rvmrc
    - f_vscode_settings
    - f_vimrc
    - f_bashrc
    - f_profile
